### ISSUE TITLE
LSST PSF fitting routine issues

### ISSUE THREAD

**Issue by fergusL** [AstroHuntsman/obs_huntsman#11]
- Having trouble detecting initial sources so need to set the threshold level lower than default (#9)

- Running with more than one iteration of the psf routine causes routine to fail for unknown reason (#9)

**Comment by danjampro** [comment]
On doing more than one iteration of initial PSF measurement, the stack was throwing errors because no detections made the PSF candidate selection cut in the later iterations. The relevant LSST code is [here](https://github.com/lsst/meas_algorithms/blob/master/python/lsst/meas/algorithms/objectSizeStarSelector.py).

In order to get more PSF candidates, one can increase the value of:
```
config.measurePsf.starSelector['objectSize'].widthStdAllowed
```

One side note is that (at least some of) the data we are using to test (i.e. that in metahunter) has a drastically different PSF across the image, which may be causing problems. We will have to tune these parameters when we have some better commissioning data.
